spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: sami
    password: sami
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostareSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true

  application:
    name: product-service
server:
  port: 8050

